export const CLEAN_IMAGE_FILTER = 'CLEAN_IMAGE_FILTER';
export const GET_IMAGES = 'GET_IMAGES';
export const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const REDO_FILTER = 'REDO_FILTER';
export const SET_IMAGE_FILTER = 'SET_IMAGE_FILTER';
export const UNDO_FILTER = 'UNDO_FILTER';
export const SET_FILTER_HISTORY = 'SET_FILTER_HISTORY';
